backend/package-lock.json
backend/package.json
backend/prisma/schema.prisma
backend/src/modules/auth/auth.controller.ts
backend/src/modules/auth/auth.service.ts
backend/src/modules/auth/dto/GitHubUser.dto.ts
backend/src/modules/auth/dto/index.ts
backend/src/modules/auth/strategy/github.strategy.ts
backend/src/modules/auth/test/index.ts

테스트 계정의 github에 repo를 생성한 뒤 push하는 로직을 구현
#8

Feature/8 게시글을 사용자의 GitHub repo에 저장

---

backend/src/modules/auth/auth.controller.ts
backend/src/modules/auth/auth.service.ts
backend/src/modules/auth/strategy/github.strategy.ts
backend/src/modules/auth/strategy/jwt.strategy.ts

JWT 인증 시 DB에 저장되었던 accessToken을 사용하지 않던 문제 해결

Fix/22 jwt 인증 시 db를 통한 검증 추가

---

frontend/src/assets/svg/ChevronLeft.svg
frontend/src/assets/svg/ChevronRight.svg
frontend/src/components/Pagination.tsx
frontend/src/pages/BlogMain.tsx

Feature/16 블로그 개인 페이지 퍼블리싱

---

frontend/package-lock.json
frontend/package.json
frontend/public/mockServiceWorker.js
frontend/src/App.tsx
frontend/src/api/api.ts
frontend/src/api/apiTypes.ts
frontend/src/components/Sidebar.tsx
frontend/src/index.tsx
frontend/src/mocks/handlers.ts
frontend/src/mocks/worker.ts
frontend/src/pages/BlogMain.tsx
frontend/src/pages/Main.tsx

closes #27 
1. msw를 이용한 기존 API mock
2. React query를 사용해서 로딩, 에러 등 상태관리
Loading 인디케이터와, Error 인디케이터가 현재 단순 텍스트 span으로만 되어 있음, 시각적으로 원활한 형태로 변경해야 함

FE 사이드 data fetching mocking

---

frontend/src/components/PostGrid.tsx
frontend/src/pages/BlogMain.tsx
frontend/src/pages/Main.tsx

Feature/21 featuredpost 컴포넌트 수정 요청

---

backend/prisma/schema.prisma
backend/src/modules/article/article.service.ts
backend/src/modules/auth/auth.service.ts
backend/src/modules/auth/test/index.ts
backend/src/modules/auth/token.service.ts
backend/src/modules/prisma/prisma.service.ts
backend/src/types/Env.ts
backend/src/types/index.ts

35 테스트용 서버 계정을 배포용 서버 계정으로 변경

---

.github/workflow/main.yml
package.json

현재 yml 파일을 통한 github actions 실행을 확인해보고 있으며 서버에 자동으로 upload하고 build 작업까지 완료할 수 있는지 확인하고 있습니다.

Github actions 설정.

---

backend/src/modules/auth/auth.service.ts
backend/src/modules/auth/dto/Email.dto.ts
backend/src/modules/auth/dto/index.ts

회원가입 시 사용자의 이메일이 private한 경우 사용자의 이메일을 가져오지 못하던 오류를 수정
fix #44

feat(backend/modules/auth): 회원가입 시 이메일이 들어오지 않는 오류를 수정

---

backend/ecosystem.config.js
backend/src/modules/app.controller.ts

main으로 push 이벤트 발생시 발생하는 과정 테스트.

test(backend): 배포 자동화 및 무중단 배포 테스트, health check 경로 추가 테스트

---

backend/src/main.ts
backend/src/modules/auth/auth.service.ts
frontend/src/api/api.ts
frontend/src/api/apiTypes.ts
frontend/src/components/Header.tsx
frontend/src/components/NewPost/NewPostBody.tsx
frontend/src/index.tsx
frontend/src/pages/Main.tsx

Feature/48 메인페이지 로그인 유무확인 링크작업

---

backend/src/modules/article/article.service.ts
backend/src/modules/article/dto/Article.dto.ts
backend/src/modules/article/dto/ArticleResponse.dto.ts
backend/src/modules/article/swagger/readone.swagger.ts

게시글을 하나 가져올 때는 게시글의 정보를 최대한 상세하게, 게시글에 CUD 연산을 행한 경우 게시글의 id와 작성자 id를 포함하도록 변경
feat #28

feat(backend/modules/article): articleModule에서 반환하는 값을 구체화

---

backend/src/modules/auth/auth.controller.ts
backend/src/types/Env.ts

로그인 및 로그아웃 시 돌아갈 페이지의 url을 환경 변수로 지정
refactor #55

feat(backend/auth): 로그인 및 로그아웃 시 redirect할 url을 .env로 지정

---

backend/.gitignore
backend/package-lock.json
backend/package.json
backend/src/modules/app.module.ts
backend/src/modules/image/dto/index.ts
backend/src/modules/image/dto/url.dto.ts
backend/src/modules/image/image.controller.ts
backend/src/modules/image/image.module.ts
backend/src/modules/image/image.service.ts
backend/src/modules/image/swagger/index.ts
backend/src/modules/image/swagger/upload.swagger.ts
backend/src/types/Env.ts

ncloud object storage에 저장하는 방식으로 진행해보았습니다. 확인해주시고 merge 해주시면 감사하겠습니다.

61 image 업로드 및 가져오기 api

---

frontend/src/App.tsx
frontend/src/api/api.ts
frontend/src/api/apiTypes.ts
frontend/src/components/Header.tsx
frontend/src/components/NewPost/NewPostBody.tsx
frontend/src/components/Post/PostContent.tsx
frontend/src/components/Post/PostHead.tsx
frontend/src/pages/BlogMain.tsx
frontend/src/pages/Main.tsx
frontend/src/pages/NewPost.tsx
frontend/src/pages/Post.tsx

58 게시글 조회 페이지 
카테고리와 댓글은 아직 추가하지 않았습니당

58 게시글 조회 페이지

---

backend/src/modules/article/db.service.ts
backend/src/modules/article/dto/Filter.dto.ts

게시글 목록 조회 시 게시글 제목에 특정 문자열이 들어가도록 검색 조건을 수정
feat #82

feat(backend/article): 게시글 목록 조회 시 게시글 제목을 이용해 filter를 걸 수 있도록 변경

---

backend/prisma/schema.prisma
backend/src/modules/auth/auth.service.ts
backend/src/modules/auth/strategy/index.ts
backend/src/modules/blog/blog.controller.ts
backend/src/modules/blog/blog.service.ts
backend/src/modules/blog/dto/Patch.dto.ts
backend/src/modules/blog/dto/index.ts

Feature/84 사용자 및 블로그 정보 수정 api 생성

---

backend/src/modules/image/image.controller.ts
backend/src/modules/image/image.service.ts

상헌님의 의견에 따라 S3의 객체를 재사용하기 위해서 constructor에 S3 객체 저장.

refactor(backend): 불필요한 res 객체 삭제. S3 객체를 만들어놓고 필요할 때 가져와서 사용하는 방식으로 변경

---

backend/src/modules/app.controller.ts
backend/src/modules/article/db.service.ts
backend/src/modules/article/dto/Filter.dto.ts
backend/src/modules/article/dto/Response.dto.ts
backend/src/modules/article/dto/Upsert.dto.ts
backend/src/modules/blog/blog.controller.ts
backend/src/modules/blog/blog.service.ts
backend/src/modules/blog/dto/Patch.dto.ts
backend/src/modules/blog/dto/Response.dto.ts
backend/src/modules/blog/dto/index.ts
backend/src/modules/blog/swagger/Get.swagger.ts
backend/src/modules/blog/swagger/Patch.swagger.ts
backend/src/modules/blog/swagger/index.ts
backend/src/modules/category/category.controller.ts
backend/src/modules/tag/swagger/Get.swagger.ts
backend/src/modules/tag/swagger/index.ts
backend/src/modules/tag/tag.controller.ts

docs(backend): 기존의 누락되어 있던 swagger를 채워넣음

---

frontend/src/api/api.ts
frontend/src/api/apiTypes.ts
frontend/src/components/Header.tsx
frontend/src/components/IntroBanner.tsx
frontend/src/components/PostCard.tsx
frontend/src/components/PostGrid.tsx
frontend/src/pages/BlogMain.tsx
frontend/src/pages/Main.tsx

Feature/ 81 블로그 메인페이지 api연결

---

backend/src/modules/blog/blog.service.ts
backend/src/modules/blog/dto/Patch.dto.ts
backend/src/modules/blog/dto/Response.dto.ts

사용자 정보를 수정할 때 닉네임 역시 수정할 수 있도록 설정

feat(backend/blog): 닉네임 수정 API 생성

---

backend/src/modules/blog/dto/Patch.dto.ts

사용자의 SNS 링크에 대한 설명을 swagger에 추가
docs #86

docs(backend/blog): swagger 설정

---

frontend/src/pages/Admin/PersonalInfoManage.tsx

admin 페이지에서 사용자가 로그인한 상태라면 사용자 ID를 가져온 뒤, 사용자 ID를 이용해 블로그 정보를 받아 그를 기반으로 setState함수를 호출
feat #76

feat(frontend/admin): admin 페이지에서 현재 로그인한 사용자에 따라 페이지의 input값을 변경

---

backend/src/modules/blog/blog.service.ts

snsLink가 undefined일 때 snsLink의 map을 참조하여 버그가 발생하던 오류를 수정

fix(backend/blog): snsLink가 undefined일 때 버그가 발생하지 않도록 수정

---

backend/src/modules/blog/blog.service.ts
frontend/src/api/api.ts

API 요청을 보낼 때 dto를 body로, headers의 Content-type을 application/json으로 설정

fix(frontend/api): aPI 요청을 보낼 때 body와 headers를 설정

---

frontend/src/api/api.ts
frontend/src/api/apiTypes.ts
frontend/src/components/Sidebar.tsx
frontend/src/pages/BlogMain.tsx
frontend/src/pages/Post.tsx

SideBar Components에서 백엔드 API를 이용해 사용자 정보를 받아오도록 수정

Feature/106 사이드바 api 연결

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Post.tsx

closes #113 
https://www.npmjs.com/package/utterances-react-component 이용

113 게시글에 Utterances 부착

---

frontend/src/editor/guideLine.ts
frontend/src/editor/mdxComponent.ts
frontend/src/pages/Search.tsx
frontend/src/styles/editor.css

feat(fe): 가이드라인 수정

---

backend/src/modules/app.module.ts
backend/src/modules/user/user.controller.ts
backend/src/modules/user/user.module.ts

사용자 정보에 관련된 작업을 진행할 예정이었던 user 모듈을 삭제

refactor(backend/user): 사용하지 않는 모듈 삭제

---

backend/src/modules/auth/auth.controller.ts
backend/src/modules/auth/dto/User.dto.ts
frontend/src/api/apiTypes.ts
frontend/src/components/Header.tsx

Feature/ 116 헤더 프로필 사진 이슈

---

frontend/src/components/NewPost/TagSelector.tsx

closes #129
- 스크롤 기능 추가
- 검색 기능(대소문자 구분 X)

129 태그 컴포넌트 개선

---

backend/src/modules/auth/auth.controller.ts
backend/src/modules/auth/session.service.ts
backend/src/modules/auth/strategy/jwt.strategy.ts

로그인 시 토큰 생성과 쿠키 생성을 login 메소드 안에서 동시에 진행하도록 변경

refactor(backend/auth): 로그인 시 토큰 생성과 쿠키 생성을 동시에 진행
